export default {
    modes: ["net", "ai", "server", "hotseat"],
    mode: "net",
    connections: ["webrtc", "websocket"],
    connection: "websocket",
    wsPort : 8088,
    loggerAnchor: ".log",
    logLevel: 7,
    cardsDeal: 7,
    botCount: 2,
    playerIsBot: false,
    idNameInStorage: "my-id",
    idNameLen : 6,
    maxClickToBan: 5,
    maxScore: 500,
    showAll: false,
    clickAll: false,
    show: true,
    applyEffects: true,
    lastCardNoColor: true,
    legacyView: false,
    colorOrder: ["red", "yellow", "green", "blue", "black"],
    sortByColor: "",
    direction: ["center"],
    seed: "",
    movePause: 150,
    botMovePause: 700,
    botSecondMovePause: 300,
    dealAnim: 500,
    discardAnimBeforeFlip: 100,
    discardAnimAfterFlip: 800,
    betweenRounds: 900,
    beforeChooseDealer: 100,
    drawShow: 200,
    drawMy: 120,
    drawClosed: 50,
    beforeDeal: 100,
    shufflePause: 300,
    changeCurrentPause: 50,
    moveAnim: 250,
    maxNameLen: 15
};
